version: '3.8'

services:
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_URI=mongodb://mongo:27017
      - RPC_PROVIDER=http://host.docker.internal:8545
